---
- hosts: all
  roles:
    - aptitude
    - utils
    - docker
    - role: api
      vars:
        image_docker: "{{ image_git_registry_api }}"
        name_container_docker: ldt-api
        name_container_published_ports_docker: 3000:3001
        username_docker: "{{ username_git_registry }}"
        password_docker: "{{ password_git_registry }}"
        registry: "{{ url_git_registry }}"
    - role: web
      vars:
        image_docker: "{{ image_git_registry_interface }}"
        name_container_docker: ldt-interface
        name_container_published_ports_docker: 80:80
        username_docker: "{{ username_git_registry }}"
        password_docker: "{{ password_git_registry }}"
        registry: "{{ url_git_registry }}"