---
- name: Install required system packages
  apt: name={{ item }} update_cache=yes state=latest 
  loop: ['apt-transport-https','ca-certificates','curl','software-properties-common','python3-pip','virtualenv','python3-setuptools']