---
- name: "Login docker with {{ username_docker }}"
  docker_login:
    registry_url: "{{ registry }}"
    username: "{{ username_docker }}"
    password: "{{ password_docker }}"
    reauthorize: yes

- name: "Create container for {{ name_container_docker }}"
  docker_container:
    image: "{{ image_docker }}"
    name: "{{ name_container_docker }}"
    published_ports:
      - "{{ name_container_published_ports_docker }}"
    
- name: Logout docker
  docker_login:
    state: absent