---
- name: Add docker GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add doker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  pip:
   name: docker

- name: "Login docker with {{ username }}"
  docker_login:
    registry_url: "{{ registry }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: "Create containers"
  docker_container:
    image: "{{ item.image }}:{{ item.version }}"
    name: "{{ item.name }}"
    published_ports:
      - "{{ item.ports }}"
  loop: "{{ containers }}"
    
- name: Logout docker
  docker_login:
    state: absent